import os
import json
from sbux_model.io import read_table, save_table
from sbux_model import features as ft

CONFIG_PATH = "src/config/features_config.json"

# Load JSON config
with open(CONFIG_PATH, "r") as f:
    config = json.load(f)

stage_name = config["stage_name"]
input_stage = config["input_stage"]
feature_defs = config.get("features", {})

# Load preprocessed table
df = read_table(stage_name=input_stage, config=config.get("input"))

# ----------------------------------------------------
# 1. Compute RETURNS and TARGET (Expected Excess Return)
# ----------------------------------------------------
df = ft.compute_residual_alpha(df, asset_col="SBUX", benchmark_col="SPY", window=52)

# ----------------------------------------------------
# 2. Apply feature engineering from JSON specs
# ----------------------------------------------------
for feat_name, feat_cfg in feature_defs.items():
    ft.apply_feature(df, feat_cfg)

# ----------------------------------------------------
# 3. Drop NA generated by rolling/lag + final rows with no target
# ----------------------------------------------------
df.dropna(inplace=True)

# ----------------------------------------------------
# 4. Save output
# ----------------------------------------------------
output_path = save_table(df, stage_name, config.get("output"))
print(f"Saved features table → {output_path}")
