import os
import json
from sbux_model.io import read_table, save_table
from sbux_model import features as ft

CONFIG_PATH = "src/config/features_config.json"

# Load JSON config
with open(CONFIG_PATH, "r") as f:
    config = json.load(f)

stage_name = config["stage_name"]
input_stage = config["input_stage"]
feature_defs = config.get("features", {})

# Load preprocessed table
df = read_table(stage_name=input_stage, config=config.get("input"))

# ----------------------------------------------------
# 1. Compute RETURNS and TARGET (Expected Excess Return)
# ----------------------------------------------------
df = ft.compute_residual_alpha(df, asset_col="SBUX", benchmark_col="SPY", window=52)

# ----------------------------------------------------
# 2. Apply feature engineering from JSON specs
# ----------------------------------------------------
for feat_name, feat_cfg in feature_defs.items():
    ft.apply_feature(df, feat_cfg)

# ----------------------------------------------------
# 3. Drop NA generated by rolling/lag + final rows with no target
# ----------------------------------------------------
print("\nNaN count per column (before dropna):")
nan_counts = df.isna().sum()
print(nan_counts[nan_counts > 0].sort_values(ascending=False))

# Ignore first 52 rows (warmup)
rows_with_nans = df.copy()
rows_with_nans["num_nans"] = rows_with_nans.isna().sum(axis=1)
rows_with_nans = rows_with_nans.iloc[52:][rows_with_nans.iloc[52:]["num_nans"] > 0]

if len(rows_with_nans) > 0:
    # List dates and number of NaNs per row
    rows_with_nans["nan_columns"] = rows_with_nans.apply(lambda r: list(r[r.isna()].index), axis=1)
    print("\nDates with NaNs (excluding first 52 warmup rows):")
    print(rows_with_nans[["num_nans", "nan_columns"]])
else:
    print("\nNo NaNs found after first 52 rows.")

df.dropna(inplace=True)

# ----------------------------------------------------
# 4. Save output
# ----------------------------------------------------
output_path = save_table(df, stage_name, config.get("output"))
print(f"Saved features table → {output_path}")
